### ISSUE TITLE
Portrait UI orientation not work in 1.24.2?

### ISSUE THREAD

**Issue by ghost** [chengxinlun/Stellarium-android#5]
Currently 1.24.2 not follow device rotation and locked in album mode. Is it ussue? In 1.24.1 all work normal

Android 6.0

**Comment by chengxinlun** [comment]
I cannot reproduce the bug. Could you please send me the log file or the ```adb logcat``` output?

**Comment by chengxinlun** [comment]
I used the old AndroidManifest.xml. Will fix that soon.

**Comment by chengxinlun** [comment]
Fixed in https://github.com/chengxinlun/Stellarium-android/commit/943341330955e79c382201174fdcae337ffe772c. Will build and release soon.
